project:
  type: website

website:
  title: "."
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



