project:
  type: website

website:
  title: "CEN5035"
  navbar:
    background: 'white'
    left:
      - href: index.qmd
        text: home
      - href: blog.qmd
        text: blog

format:
  html:
    theme: morph
    toc: true
